version: '3.5'

services:

  k12-angular-starter:
    container_name: k12-angular-starter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - '.:/usr/src/app'
    - '/usr/src/app/node_modules'
    ports:
    - '4200:4200'
